### ISSUE TITLE
Create 3D ASCII logo

### ISSUE THREAD

**Issue by LOZORD** [LOZORD/xanadu#10]
Post choices in this thread

**Comment by LOZORD** [comment]
How do people like Caligraphy2 via patorjk.com?

```

  ###          ##                                         ##                 
 /####       ####  /                                       ##                
/   ###      /####/                                        ##                
     ###    /   ##                                         ##                
      ###  /                                               ##                
       ###/              /###   ###  /###     /###     ### ##  ##   ####     
        ###             / ###  / ###/ #### / / ###  / ######### ##    ###  / 
        /###           /   ###/   ##   ###/ /   ###/ ##   ####  ##     ###/  
       /  ###         ##    ##    ##    ## ##    ##  ##    ##   ##      ##   
      /    ###        ##    ##    ##    ## ##    ##  ##    ##   ##      ##   
     /      ###       ##    ##    ##    ## ##    ##  ##    ##   ##      ##   
    /        ###      ##    ##    ##    ## ##    ##  ##    ##   ##      ##   
   /          ###   / ##    /#    ##    ## ##    /#  ##    /#   ##      /#   
  /            ####/   ####/ ##   ###   ### ####/ ##  ####/      ######/ ##  
 /              ###     ###   ##   ###   ### ###   ##  ###        #####   ## 



```

**Comment by mhorowitzgelb** [comment]
Or this pipe

                                                                                       ```.``      
                                                                                    .+syysso+/:.    
                                                                                  `-shddhyso++++/   
                                                                                  `oddddddhyooosy-  
                                                                                 `-sddddddddyooys.  
                          `           `````````                                  `:+yddddddhhhy+`   
                   ``..-:/o/.-::::/+ooosssssssoo+/:-.```                          .-+syhhdddh+.     
           ``..-:///++oosyyyshhhsso+//:--..--:/+osyyyyyyo/::.`                     `./oooydho:.     
   -..--://++++oooooosssyhhho--..                ``-:+yhdhhhys+:-.``             ``.-/oyddhhhys/    
  -sooooooooooooooo++++++//:-                         `+yyoo++osyyysoo++/++++++ooyyhhydhddddysos.   
 `:oso+///:::-....``````                                ....---::--:://++++++++oysssssyydddddhho`   
  `.-.`                                                        `......`     `..-`` ```.-/oyhdy-     
                                                                      `......`         ````.``

**Comment by max-billion** [comment]
or THis pipe

````````````
                                                                                   ```.``      
                                                                                .+syysso+/:.    
                                                                              `-shddhyso++++/   
                                                                              `oddddddhyooosy-  
                                                                             `-sddddddddyooys.  
                      `           `````````                                  `:+yddddddhhhy+`   
               ``..-:/o/.-::::/+ooosssssssoo+/:-.```                          .-+syhhdddh+.     
       ``..-:///++oosyyyshhhsso+//:--..--:/+osyyyyyyo/::.`                     `./oooydho:.     
````````````

   -..--://++++oooooosssyhhho--..                `-:+yhdhhhys+:-.`             `.-/oyddhhhys/    
  -sooooooooooooooo++++++//:-                         `+yyoo++osyyysoo++/++++++ooyyhhydhddddysos.   
 `:oso+///:::-....``....---::--:://++++++++oysssssyydddddhho`   
  `.-.`                                                        `......`     `..-`` ```.-/oyhdy-     
                                                                      `......``.``

**Comment by max-billion** [comment]
Wait that didn't come out well

> ````````````
>                                                                                    ```.``      
>                                                                                 .+syysso+/:.    
>                                                                               `-shddhyso++++/   
>                                                                               `oddddddhyooosy-  
>                                                                              `-sddddddddyooys.  
>                       `           `````````                                  `:+yddddddhhhy+`   
>                ``..-:/o/.-::::/+ooosssssssoo+/:-.```                          .-+syhhdddh+.     
>        ``..-:///++oosyyyshhhsso+//:--..--:/+osyyyyyyo/::.`                     `./oooydho:.     
> ````````````
> 
>    -..--://++++oooooosssyhhho--..                `-:+yhdhhhys+:-.`             `.-/oyddhhhys/    
>   -sooooooooooooooo++++++//:-                         `+yyoo++osyyysoo++/++++++ooyyhhydhddddysos.   
>  `:oso+///:::-....``....---::--:://++++++++oysssssyydddddhho`   
>   `.-.`                                                        `......`     `..-`` ```.-/oyhdy-     
>                                                                       `......``.``

**Comment by max-billion** [comment]
Ok neither did that.  Here's this

[pipe ascii.txt](https://github.com/LOZORD/xanadu/files/226906/pipe.ascii.txt)

**Comment by LOZORD** [comment]
Is that supposed to be a pipe? And why a pipe? 😖

**Comment by max-billion** [comment]
it's an opium pipe

**Comment by LOZORD** [comment]
Lol, god dammit... that's not the entire game you know!!! 😆

**Comment by LOZORD** [comment]
```
▀████    ▐████▀    ▄████████ ███▄▄▄▄      ▄████████ ████████▄  ███    █▄  
  ███▌   ████▀    ███    ███ ███▀▀▀██▄   ███    ███ ███   ▀███ ███    ███ 
   ███  ▐███      ███    ███ ███   ███   ███    ███ ███    ███ ███    ███ 
   ▀███▄███▀      ███    ███ ███   ███   ███    ███ ███    ███ ███    ███ 
   ████▀██▄     ▀███████████ ███   ███ ▀███████████ ███    ███ ███    ███ 
  ▐███  ▀███      ███    ███ ███   ███   ███    ███ ███    ███ ███    ███ 
 ▄███     ███▄    ███    ███ ███   ███   ███    ███ ███   ▄███ ███    ███ 
████       ███▄   ███    █▀   ▀█   █▀    ███    █▀  ████████▀  ████████▀  

```

Delta Corps Priest 1

**Comment by LOZORD** [comment]
```
 ▄▀▀▄  ▄▀▄  ▄▀▀█▄   ▄▀▀▄ ▀▄  ▄▀▀█▄   ▄▀▀█▄▄   ▄▀▀▄ ▄▀▀▄ 
█    █   █ ▐ ▄▀ ▀▄ █  █ █ █ ▐ ▄▀ ▀▄ █ ▄▀   █ █   █    █ 
▐     ▀▄▀    █▄▄▄█ ▐  █  ▀█   █▄▄▄█ ▐ █    █ ▐  █    █  
     ▄▀ █   ▄▀   █   █   █   ▄▀   █   █    █   █    █   
    █  ▄▀  █   ▄▀  ▄▀   █   █   ▄▀   ▄▀▄▄▄▄▀    ▀▄▄▄▄▀  
  ▄▀  ▄▀   ▐   ▐   █    ▐   ▐   ▐   █     ▐             
 █    ▐            ▐                ▐                   
```

THIS (font name)

**Comment by LOZORD** [comment]
```
             ..                                            ..                      
   .H88x.  :~)88:                                        dF                        
  x888888X ~:8888                u.    u.               '88bu.         x.    .     
 ~   "8888X  %88"       u      x@88k u@88c.       u     '*88888bu    .@88k  z88u   
      X8888          us888u.  ^"8888""8888"    us888u.    ^"*8888N  ~"8888 ^8888   
   .xxX8888xxxd>  .@88 "8888"   8888  888R  .@88 "8888"  beWE "888L   8888  888R   
  :88888888888"   9888  9888    8888  888R  9888  9888   888E  888E   8888  888R   
  ~   '8888       9888  9888    8888  888R  9888  9888   888E  888E   8888  888R   
 xx.  X8888:    . 9888  9888    8888  888R  9888  9888   888E  888F   8888 ,888B . 
X888  X88888x.x"  9888  9888   "*88*" 8888" 9888  9888  .888N..888   "8888Y 8888"  
X88% : '%8888"    "888*""888"    ""   'Y"   "888*""888"  `"888*""     `Y"   'YP    
 "*=~    `""       ^Y"   ^Y'                 ^Y"   ^Y'      ""                     



```

Fraktur

**Comment by LOZORD** [comment]
```
.##.....##....###....##....##....###....########..##.....##
..##...##....##.##...###...##...##.##...##.....##.##.....##
...##.##....##...##..####..##..##...##..##.....##.##.....##
....###....##.....##.##.##.##.##.....##.##.....##.##.....##
...##.##...#########.##..####.#########.##.....##.##.....##
..##...##..##.....##.##...###.##.....##.##.....##.##.....##
.##.....##.##.....##.##....##.##.....##.########...#######.
```

banner4 from http://www.network-science.de/ascii/

I like this one because it looks like the map 😋

**Comment by LOZORD** [comment]
Not 3D or ASCII, but still very cool:

https://www.google.com/fonts/specimen/UnifrakturCook

**Comment by LOZORD** [comment]
I like having everything monospace (Nova Mono) for now. We'll go with [the ASCII Fraktur logo](http://patorjk.com/software/taag/#p=display&f=Fraktur&t=Xanadu).
