### ISSUE TITLE
Move to TypeScript 2.0 or higher

### ISSUE THREAD

**Issue by LOZORD** [LOZORD/xanadu#35]

**Comment by LOZORD** [comment]
We should use this flag and update code as necessary: https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#--strictnullchecks

**Comment by jimbuck** [comment]
I just completed this on a 1000+ file commercial project (while upgrading Angular 2-rc3 app to Angular 2.1). No major changes need to be made, but `typings` is obselete (in favor of `@types/*`).

As for `strictNullChecks`, that might be best as a separate PR/commit. Dependending on how many changes that requires it might be best to easily roll back if needed.

**Comment by LOZORD** [comment]
Thanks for your interest, but I've already started work on a PR for this one.

There's a lot of annoying fixes with `strictNullChecks`, so I doubt it'd be fun for you to work on 😅

**Comment by jimbuck** [comment]
Haha, I figured enabling that flag would be better suited for you. Best of luck!

**Comment by LOZORD** [comment]
Yeah I definitely want to use strict null checking. I've already started
work on a (close to published) PR. Thanks for your interest though.
