### ISSUE TITLE
Clean up NPM warnings

### ISSUE THREAD

**Issue by katamaritaco** [LOZORD/xanadu#66]
When attempting to get Xanadu up and running for the first time, during the 'npm install' step, there are 3 deprecation warnings.

npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.

npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade

npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

**Comment by LOZORD** [comment]
tl;dr: not my problem (as long as everything works)

See [here](https://github.com/npm/npm/issues/11628) and [here](http://stackoverflow.com/questions/34840153/npm-deprecated-warnings-do-i-need-to-update-something)

You are welcome to make a PR with an updated `package.json` if the deprecation warnings go away with updated "core" packages.
