### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by jimbuck** [LOZORD/xanadu#72]
There were really only two changes that needed to be made to get up and running on Windows.
1. A few minor build differences that must be updated, specifically the use of single quotes in the `test:cover` command.
2. The platform-dependent character `\n` was hardcoded for grid parsing (and thus breaking). It should be using `EOL` from Node's `os` (platform-specific newline character).

**Comment by LOZORD** [comment]
Thanks for your help on this! I've been doing dev mainly on Mac and a little bit on Linux 😅  Do you want to go ahead and [add Windows](https://docs.travis-ci.com/user/multi-os/) to `.travis.yml`?

**Comment by jimbuck** [comment]
Setting up CI, no problem. Although Travis does not support Windows. If you sign up for [AppVeyor](https://www.appveyor.com/) then I can configure that accordingly, it works almost the same way.

**Comment by LOZORD** [comment]
AppVeyor looks nice 👌  I will set up the build this weekend and merge #73 once it's up and running. Thanks again for your help on this.

**Comment by LOZORD** [comment]
Ok, I signed up for AppVeyor and added the project. If you have experience with AppVeyor, could you please write the yaml file? Otherwise, I can do it.

**Comment by jimbuck** [comment]
Yes, I have used it before. I'll try and get it configured this weekend.

**Comment by LOZORD** [comment]
Well, the project builds now, but there seems to be a problem with a map validation test. I will investigate.

https://ci.appveyor.com/project/LOZORD/xanadu/build/1.0.14#L207

So testing for the missing treasure room is the first check when validating a map. It seems that the map is malformed -- probably due to line endings.

**Comment by LOZORD** [comment]
Please also change `test:cover` to the following (otherwise we include *Spec files in coverage):

``` json
    "test:cover": "istanbul cover \"dist/test.js\" --include-all-sources --root \"dist\" -x \"test.js\" -x \"**/*Spec.js\""
```

**Comment by LOZORD** [comment]
Had some time to kill... looks like I got everything under control finally 😸 . This _should_ be good now!

Thanks again for your help @JimmyBoh.

**Comment by jimbuck** [comment]
Ah, sorry I couldn't address it earlier! Keep up the great work!

**Comment by LOZORD** [comment]
No worries! Please let me know if you ever want to tackle another issue.
