### ISSUE TITLE
Add `david` and update dependencies

### ISSUE THREAD

**Issue by LOZORD** [LOZORD/xanadu#77]
This one should be pretty cut and dry, and especially choice for Hacktoberfest 🎃 
1. Add `david` to `devDependencies`
2. Update any old packages according to `david`; resolve any errors according to tests
3. Add `david` as a `script` in `package.json` (preferably `preinstall`)

**Comment by dudraj** [comment]
@LOZORD Can I work on this project.

**Comment by LOZORD** [comment]
Sorry, @dudraj , it looks like @oishikatta has already started work in #78 

#41, #46, or #8 (with respect to source maps) would be nice issues for you to tackle 😄

**Comment by LOZORD** [comment]
@oishikatta, actually `preinstall` won't work because `david` won't be installed yet 😅 whoops 
Try `postinstall` instead. Also, I merged #74 , so those issues you mentioned should be resolved.
