### ISSUE TITLE
Add testing

### ISSUE THREAD

**Issue by LOZORD** [LOZORD/xanadu#8]
Testings should be ran as `npm run test`. I'm enforcing (:sunglasses:) that we use Mocha, Chai, and Sinon for testing (as `devDependencies`). The testing directory `test/` structure should mimic exactly the structure of `dist/` (which mimics `src/` via Babel).

**Comment by LOZORD** [comment]
It might be good to have a `test-src` directory that, via Babel, goes to `test-dist`. In short, the test code should be in ES6.

**Comment by LOZORD** [comment]
Thanks for your help on the `mvc` branch @zthomae 🎉  ! Do you think it is worth it to add [Istanbul](https://github.com/gotwarlost/istanbul)?

I will add Sinon if it becomes useful.

**Comment by LOZORD** [comment]
@zthomae I think we should close this when `mvc` gets merged into `master`. Agree?

**Comment by zthomae** [comment]
I wouldn't want to close this until most of the things that we want to have tests have them. Whether this happens before or after it gets merged is up to you.

Istanbul might be useful for this, but I don't know if it's essential.

**Comment by LOZORD** [comment]
Do you think that the test code should go in its own directory (not inside `src`)? We could have Babel build something like `distTest` and then run Mocha on that.

**Comment by zthomae** [comment]
I think that the proper location for test files is alongside their corresponding source files. See d318ba4512a63b5aa227932f6fcf1a49b5e5b8fe

**Comment by LOZORD** [comment]
If it works for Mr. Pike, it works for me 😁

**Comment by LOZORD** [comment]
I attempted to add Istanbul using [this tutorial](https://egghead.io/lessons/javascript-how-to-write-a-javascript-library-adding-code-coverage-recording-with-istanbul) using this command:

``` brew
$ node_modules/istanbul/lib/cli.js cover -x ./dist/**/*Spec.js node_modules/mocha/bin/_mocha -- -R spec ./dist/**/*Spec.js
```

Didn't seem to work correctly, as only coverage was generated for `dist/game`.

**Comment by LOZORD** [comment]
Might be good to include: http://elijahmanor.com/npm-precommit-scripts/

**Comment by LOZORD** [comment]
Added Istanbul -- see 72187ce. **BUT** it only works if I don't exclude the `*Spec.js` files, as was seen with the previous command above. I will investigate (starting with https://github.com/gotwarlost/istanbul/issues/44) and create an issue there if necessary.

**Comment by LOZORD** [comment]
Got it: 54128c4

**Comment by LOZORD** [comment]
There's an issue with testing: mocha does not find tests in the "deep" subdirectories. We need to use something more general than `dist/**/*Spec.js`.

This might be helpful: https://gist.github.com/timoxley/1721593

But it might not be great for Windows support 😕

**Comment by LOZORD** [comment]
https://github.com/Izhaki/Typescript-Mocha-Istanbul-Boilerplate

@zthomae, do you think this would be useful?

**Comment by LOZORD** [comment]
http://stackoverflow.com/questions/34890907/how-to-test-es6-module-that-imports-jquery-with-jsdom

**Comment by LOZORD** [comment]
I will eventually push my VSCode project configuration into the repo. I'm definitely not mandating that VSCode be used for everything (I'm still a vim fanboy), but this debugging (re: TS/JS source maps) might be helpful:

https://code.visualstudio.com/docs/editor/debugging#_node-debugging

**Comment by LOZORD** [comment]
Closing this issue, as the only remaining thing seems to be #80
